[project]
name = "deeplearning"
version = "0.1.0"
description = "A PyTorch-based deep learning course"
readme = "README.md"
requires-python = ">=3.11,<3.12"
dependencies = [
    "torch>=2.0.0",
    "numpy>=1.24.0",
    "imageio",
    "matplotlib",
    "pandas"
]
